const Intron = sequelize.define("intron", {
  intronId: { type: DataTypes.INTEGER, primaryKey: true, allowNull: false },
  intronType: { type: DataTypes.CHAR(3), allowNull: true },
  subtype: { type: DataTypes.CHAR(3), allowNull: true },
  intronStartCoord: { type: DataTypes.BIGINT, allowNull: true },
  intronSequence: { type: DataTypes.CHAR(20000), allowNull: true },
  rank: { type: DataTypes.INTEGER, allowNull: true },
  intronLength: { type: DataTypes.INTEGER, allowNull: true },
  branchPoint: { type: DataTypes.CHAR, allowNull: true },
  acceptorSpliceSite: { type: DataTypes.CHAR, allowNull: true },
  strand: { type: DataTypes.BOOLEAN, allowNull: true },
  cluster: { type: DataTypes.INTEGER, allowNull: true },
  frame: { type: DataTypes.INTEGER, allowNull: true },
  chromosome: { type: DataTypes.CHAR, allowNull: true },
  intronEndCoord: { type: DataTypes.BIGINT, allowNull: true },
  donorSpliceSite: { type: DataTypes.CHAR, allowNull: true },
});
